version: '{build}'
image: Visual Studio 2019
environment:
#  NUGET_API_KEY:
#    secure: ***************************
  MYGET_API_KEY:
    secure: +Rg+DiRK9EmLNW3xBMP5Gv/S6iJaTvFmOd2UA4hYKlbHbJXfpA0tW0Sf4XS7YbWp

build_script:
- cmd: PowerShell .\build.ps1 --PushPackages="true"
test: off
