version: '{build}'
image: Visual Studio 2019
environment:
  NUGET_API_KEY:
    secure: ***************************
  MYGET_API_KEY:
    secure: ***************************

build_script:
- cmd: PowerShell .\build.ps1 --PushPackages="true"
test: off
